### ISSUE TITLE
`where` function

### ISSUE THREAD

**Issue by rmrhz** [prjkt/repofuck#61]

**Comment by makoru-hikage** [comment]
How must it work? Is it a simple `where()` method that will be called by `$this->entity`?

**Comment by rmrhz** [comment]
Actually this extends the functionality of the where function of whatever is assigned to the `$entity` property. If you have ideas on the functionality, please outline them in the discussion.

**Comment by makoru-hikage** [comment]
So, a new property of `class Repofuck` must be added. The things that might be needed are:
- A protected property called `$where` which starts as an empty variable, it is a `Builder`
- A public method called `setWhere()` that sets `$where`. It has two arguments, `$query` and `$append`. The `$append` is bool; if it is `true`, it'll append the supplied where clause, otherwise, the where clause is overwritten.
- If `$where` has an appropriate `Builder`, calling the `get()` will execute with the where clause. 

This solution is quite crude and yet to be made elegant.

**Comment by rmrhz** [comment]
No need to create a property but a function. Since the entity is already persisted within the repository, then you only need to use that. You'll notice that other repository abstract class implementations have `first` or `find` functions. These functions extends the original functionality through a form of abstraction. Where you don't need to worry about what name they would be in the entities.

**Comment by makoru-hikage** [comment]
This issue is resolved.
